package com.orag.ai

/**
 * The JNI Bridge connecting the Kotlin App to the raw C++ llama.cpp engine.
 * This is where the magic happens for Hybrid (Generation + Embedding) models directly on the phone.
 */
class LlamaBridge {
    
    // Load the pre-compiled native C++ library created by CMake
    init {
        System.loadLibrary("llama_jni")
    }

    /**
     * Initializes the Hybrid LLM (e.g., Qwen 2.5 or combined Nomic) on the Android device.
     * @param modelPath The absolute path on the phone's storage to the .gguf file.
     * @return True if loaded successfully, False if out of memory or corrupted.
     */
    external fun loadModel(modelPath: String): Boolean

    /**
     * Closes the model and frees up the phone's RAM.
     */
    external fun unloadModel()

    /**
     * The True RAG Vector Search replacement!
     * Passes a chunk of text to the Hybrid model and mathematically extracts the 
     * dense embedding vector directly from the C++ layer.
     * @param text The chunk of text from the PDF.
     * @return A mathematically dense float array (e.g., 768 dimensions) representing meaning.
     */
    external fun getEmbedding(text: String): FloatArray

    /**
     * The true Generative LLM answering engine.
     * @param prompt The final prompt containing the user question and the injected RAG chunks.
     * @return The text string generated by the LLM.
     */
    external fun generateResponse(prompt: String): String
}
